### ISSUE TITLE
no prometheus version defined

### ISSUE THREAD

**Issue by marlon-nc** [cherti/PromAuthProxy#2]
Hi, thanks for your work on this tool! Trying to build this code fails now, I believe because it's pulling the latest Prometheus library which is no longer compatible.  Could you give a hint as to what version of prometheus should it use?

**Comment by cherti** [comment]
Thanks for reporting, this is now fixed in 92ea53f, PromAuthProxy was not adapted to the new PromQL-parser that has landed recently in Prometheus. Now it is and things should properly build again.

Given that PromAuthProxy uses Prometheus-internals that are not intended for outside use, it is not always apparent when those change, therefore to always define a most recent Prometheus-version this works with would likely require some Travis-magic.
